name: build and upload frontend artifact

on:
  push:
    branches:
      - main

jobs:
  on-success:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: setup node
        uses: actions/setup-node@master
        with:
          node-version: 18

      - name: install dependencies
        run: npm install

      - name: build
        run: npm run build:prod

      - name: upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: build
          path: build
