name: upload frontend artifact to s3

on:
  workflow_run:
    workflows:
      - build frontend artifact
    types:
      - completed
  push:
    branches:
      - main

jobs:
  on-success:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: download artifacts
        uses: actions/download-artifacts@master
        with:
          name: build
          path: build

      - name: Remove existing artifacts from AWS S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 rm \
          s3://${{ secrets.S3_BUCKET }} \
          --recursive \
          --region ${{ secrets.AWS_REGION }}

      - name: Deploy artifacts to AWS S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp \
          ./build s3://${{ secrets.S3_BUCKET }} \
          --recursive \
          --acl public-read \
          --region ${{ secrets.AWS_REGION }}
